import type { ReviewResponse } from "../../api/types";
import { ModuleStatus } from "../../components/ModuleStatus";
import { TimingPanel } from "../../components/TimingPanel";
import { formatConfidence } from "../../lib/formatting";

export function DetailsPanel({ review }: { review: ReviewResponse }) {
  const details = review.details;
  return <div className="details-grid"><section className="panel"><h3>执行链路</h3><dl className="kv"><div><dt>运行模式</dt><dd>{review.metadata.pipeline_mode === "cascaded" ? "快速模式" : "深度模式"}</dd></div><div><dt>路由结果</dt><dd>{review.routing?.route ?? "—"}</dd></div><div><dt>VLM 调用</dt><dd>{review.routing?.call_vlm ? "是" : "否"}</dd></div><div><dt>运行 ID</dt><dd className="mono">{review.run_id}</dd></div></dl><div className="chip-row">{review.routing?.reason_codes.map((code) => <span className="chip" key={code}>{code}</span>)}</div></section><section className="panel"><h3>模块状态</h3><ul className="module-list">{Object.entries(review.modules).map(([name, status]) => <ModuleStatus key={name} name={name} status={status} />)}</ul></section><section className="panel"><h3>耗时分解</h3><TimingPanel timing={review.timing} /></section><section className="panel"><h3>融合证据</h3>{details?.fusion_scores && <dl className="kv"><div><dt>视觉分数</dt><dd>{formatConfidence(details.fusion_scores.visual)}</dd></div><div><dt>文本分数</dt><dd>{formatConfidence(details.fusion_scores.text)}</dd></div><div><dt>VLM 分数</dt><dd>{formatConfidence(details.fusion_scores.vlm)}</dd></div></dl>}<div className="chip-row">{details?.fusion_reason_codes.map((code) => <span className="chip" key={code}>{code}</span>)}</div>{details?.fusion_evidence.map((item, index) => <p className="evidence-line" key={`${item.source}-${index}`}><strong>{item.source}</strong> · {item.description}</p>)}</section><section className="panel"><h3>版本信息</h3><dl className="kv"><div><dt>Pipeline</dt><dd>{review.metadata.pipeline_version}</dd></div><div><dt>Routing</dt><dd>{review.metadata.routing_policy_version ?? "—"}</dd></div><div><dt>Fusion</dt><dd>{review.metadata.fusion_policy_version ?? "—"}</dd></div><div><dt>Prompt</dt><dd>{review.metadata.prompt_version ?? "—"}</dd></div></dl></section></div>;
}
